services:
  pagalu-app:
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cloudflared
      - pagalu
  
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-app}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - ./tmp/mariadb:/var/lib/mysql
    networks:
      - pagalu
  
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
        ADMINER_DESIGN: mvt
        ADMINER_DEFAULT_SERVER: db
    networks:
      - pagalu

networks:
  cloudflared:
    external: true
  pagalu:
    driver: bridge